const express=require('express');
const path=require('path');
const {Pool}=require('pg');
const app=express();
const PORT=process.env.PORT||3000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
const ADMIN_USER=process.env.ADMIN_USER||'admin';
const ADMIN_PASS=process.env.ADMIN_PASS||'change-this-password';
app.use(express.json({limit:'1mb'}));
app.use(express.static(path.join(__dirname,'public')));
async function init(){
 await pool.query(`CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,price INTEGER NOT NULL DEFAULT 0,emoji TEXT DEFAULT '👕',description TEXT DEFAULT '',image TEXT DEFAULT '',active INTEGER DEFAULT 1);CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,name TEXT,phone TEXT,address TEXT,note TEXT DEFAULT '',customization JSONB DEFAULT '{}'::jsonb,items JSONB DEFAULT '[]'::jsonb,subtotal INTEGER DEFAULT 0,delivery_fee INTEGER DEFAULT 200,total INTEGER DEFAULT 0,status TEXT DEFAULT 'new',created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY,delivery_fee INTEGER DEFAULT 200);`);
 await pool.query(`ALTER TABLE products ADD COLUMN IF NOT EXISTS image TEXT DEFAULT ''`);
 await pool.query(`ALTER TABLE orders ADD COLUMN IF NOT EXISTS note TEXT DEFAULT ''`);
 await pool.query(`ALTER TABLE orders ADD COLUMN IF NOT EXISTS customization JSONB DEFAULT '{}'::jsonb`);
 await pool.query(`ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal INTEGER DEFAULT 0`);
 await pool.query(`ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_fee INTEGER DEFAULT 200`);
 if(!(await pool.query('SELECT 1 FROM settings WHERE id=1')).rows.length) await pool.query('INSERT INTO settings(id,delivery_fee) VALUES(1,200)');
 if(Number((await pool.query('SELECT COUNT(*) FROM products')).rows[0].count)===0) await pool.query(`INSERT INTO products(name,category,price,emoji,description,image) VALUES('T-Shirt personnalisé','tshirts',1200,'👕','طباعة حرارية بجودة عالية','https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85'),('Sweat personnalisé','hoodies',2000,'🧥','هودي بتصميمك الخاص','https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85'),('Mug personnalisé','mugs',800,'☕','مجات بالاسم أو الصورة','https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=85'),('Casquette personnalisée','caps',1000,'🧢','كاسكيت بتصميمك','https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=85'),('Sac personnalisé','bags',900,'👜','أكياس قماشية مخصصة','https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85')`);
}
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Basic ')){res.set('WWW-Authenticate','Basic realm="PRINT STYLE Admin"');return res.status(401).send('Login required')}const d=Buffer.from(h.slice(6),'base64').toString(),i=d.indexOf(':');const u=i>=0?d.slice(0,i):d,p=i>=0?d.slice(i+1):'';if(u!==ADMIN_USER||p!==ADMIN_PASS)return res.status(403).send('Forbidden');next()}
app.get('/api/products',async(req,res)=>{try{res.json((await pool.query('SELECT * FROM products WHERE active=1 ORDER BY id DESC')).rows)}catch(e){res.status(500).json({error:'فشل تحميل المنتجات'})}});
app.get('/api/delivery',async(req,res)=>{try{res.json({deliveryFee:Number((await pool.query('SELECT delivery_fee FROM settings WHERE id=1')).rows[0]?.delivery_fee??200)})}catch(e){res.status(500).json({error:'فشل تحميل التوصيل'})}});
app.get('/api/admin/products',auth,async(req,res)=>res.json((await pool.query('SELECT * FROM products ORDER BY id DESC')).rows));
app.post('/api/admin/products',auth,async(req,res)=>{const {name,category,price,emoji,description,image}=req.body,p=Number(price);if(!name?.trim()||!category?.trim()||!Number.isFinite(p)||p<0)return res.status(400).json({error:'بيانات المنتج غير صحيحة'});const r=await pool.query('INSERT INTO products(name,category,price,emoji,description,image) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[name.trim(),category.trim(),Math.round(p),emoji?.trim()||'👕',description?.trim()||'',image?.trim()||'']);res.json({id:r.rows[0].id})});
app.put('/api/admin/products/:id',auth,async(req,res)=>{const {name,category,price,emoji,description,image,active}=req.body,p=Number(price);if(!name?.trim()||!category?.trim()||!Number.isFinite(p)||p<0)return res.status(400).json({error:'بيانات المنتج غير صحيحة'});await pool.query('UPDATE products SET name=$1,category=$2,price=$3,emoji=$4,description=$5,image=$6,active=$7 WHERE id=$8',[name.trim(),category.trim(),Math.round(p),emoji?.trim()||'👕',description?.trim()||'',image?.trim()||'',active?1:0,req.params.id]);res.json({ok:true})});
app.get('/api/admin/settings',auth,async(req,res)=>res.json({deliveryFee:Number((await pool.query('SELECT delivery_fee FROM settings WHERE id=1')).rows[0]?.delivery_fee??200)}));
app.put('/api/admin/settings',auth,async(req,res)=>{const f=Number(req.body.deliveryFee);if(!Number.isFinite(f)||f<0)return res.status(400).json({error:'سعر التوصيل غير صحيح'});const v=Math.round(f);await pool.query('UPDATE settings SET delivery_fee=$1 WHERE id=1',[v]);res.json({ok:true,deliveryFee:v})});
app.get('/api/admin/orders',auth,async(req,res)=>res.json((await pool.query('SELECT * FROM orders ORDER BY id DESC')).rows));
app.post('/api/orders',async(req,res)=>{try{const {name,phone,address,note,customization,items}=req.body;if(!name?.trim()||!phone?.trim()||!address?.trim()||!Array.isArray(items)||!items.length)return res.status(400).json({error:'الاسم والهاتف والعنوان والسلة مطلوبة'});const ids=[...new Set(items.map(x=>Number(x.id)).filter(Number.isInteger))];const ps=(await pool.query('SELECT id,name,price,emoji FROM products WHERE id=ANY($1::int[]) AND active=1',[ids])).rows;const map=new Map(ps.map(x=>[Number(x.id),x]));const final=[];let subtotal=0;for(const x of items.slice(0,50)){const p=map.get(Number(x.id));if(!p)continue;const q=Math.min(50,Math.max(1,Math.floor(Number(x.quantity)||1)));subtotal+=Number(p.price)*q;final.push({id:Number(p.id),name:p.name,price:Number(p.price),emoji:p.emoji||'👕',quantity:q})}if(!final.length)return res.status(400).json({error:'المنتجات غير متاحة'});const fee=Number((await pool.query('SELECT delivery_fee FROM settings WHERE id=1')).rows[0]?.delivery_fee??200),total=subtotal+fee,custom={size:String(customization?.size||'').slice(0,50),color:String(customization?.color||'').slice(0,80),printPosition:String(customization?.printPosition||'').slice(0,80)};const r=await pool.query('INSERT INTO orders(name,phone,address,note,customization,items,subtotal,delivery_fee,total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[name.trim(),phone.trim(),address.trim(),String(note||'').slice(0,500),JSON.stringify(custom),JSON.stringify(final),subtotal,fee,total]);res.json({id:r.rows[0].id,subtotal,deliveryFee:fee,total})}catch(e){console.error(e);res.status(500).json({error:'حدث خطأ أثناء إرسال الطلب'})}});
app.patch('/api/admin/orders/:id',auth,async(req,res)=>{const allowed=['new','preparing','printing','ready','delivering','done','cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'حالة غير صحيحة'});await pool.query('UPDATE orders SET status=$1 WHERE id=$2',[req.body.status,req.params.id]);res.json({ok:true})});
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));
init().then(()=>app.listen(PORT,()=>console.log('PRINT STYLE running on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
